### Getting the latitude and the longitude coordinates of each neighborhood

#### Importing Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('toronto.csv')
df.head()

  Postcode      Borough                           Neighbourhood
0      M1B  Scarborough                          Malvern, Rouge
1      M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2      M1E  Scarborough       Guildwood, Morningside, West Hill
3      M1G  Scarborough                                  Woburn
4      M1H  Scarborough                               Cedarbrae

In [3]:
df_geo = pd.read_csv('https://cocl.us/Geospatial_data')
df_geo.columns = ['Postcode', 'Latitude', 'Longitude']

In [4]:
df = pd.merge(df, df_geo, on=['Postcode'], how='inner')
df = df[['Borough', 'Neighbourhood', 'Postcode', 'Latitude', 'Longitude']].copy()
df

,Borough,Neighbourhood,Postcode,Latitude,Longitude
0,Scarborough,"Malvern, Rouge",M1B,43.806686,-79.194353
1,Scarborough,"Rouge Hill, Port Union, Highland Creek",M1C,43.784535,-79.160497
2,Scarborough,"Guildwood, Morningside, West Hill",M1E,43.763573,-79.188711
3,Scarborough,Woburn,M1G,43.770992,-79.216917
4,Scarborough,Cedarbrae,M1H,43.773136,-79.239476
...,...,...,...,...,...
98,York,Weston,M9N,43.706876,-79.518188
99,Etobicoke,Westmount,M9P,43.696319,-79.532242
100,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",M9R,43.688905,-79.554724
101,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",M9V,43.739416,-79.588437
102,Etobicoke,"Northwest, West Humber - Clairville",M9W,43.706748,-79.594054

In [5]:
df.to_csv('toronto_part2.csv',index=False)